### ISSUE TITLE
is @tgchessbot down?

### ISSUE THREAD

**Issue by HassanHeydariNasab** [cxjdavin/tgchessbot#2]
Hi
today, @tgchessbot is down. why?

**Comment by cxjdavin** [comment]
Thanks for reminding me! :)
I just realised that my host (Digital Ocean) had some maintenance some time back. I forgot to reset the service after it's back up.
If you wish to host it on your own, you can follow the instructions in the README.md

**Comment by HassanHeydariNasab** [comment]
Again!

**Comment by cxjdavin** [comment]
I'm so sorry! I'm having some issues with my hosting, and am currently a little busy to settle it properly. Will to get it back up within the next week or so.

In the meantime, don't hesitate to host it on your own :)

**Comment by cxjdavin** [comment]
Should be back up now :)
Unfortunately, all the previous game data was lost :(
