### ISSUE TITLE
Yet another "check", but no end of game

### ISSUE THREAD

**Issue by vladislav805** [cxjdavin/tgchessbot#3]
![screenshot from 2017-02-15 18-59-47](https://cloud.githubusercontent.com/assets/10882576/22982266/b38626e6-f3af-11e6-9ef1-336500358573.png)
Couldn't make castling. At first, because it prohibited by the rules. Second, bot the bot thinks the game is not over, but moves, excluding castling, there not.

**Comment by schubtob** [comment]
You are addressing several points here:

1. Couldn't make castling: 
As you write, castling is not a valid move in this position.

2. tgchessbot does not detect end of game:
tgchessbot currently does not properly detect checkmate (see https://github.com/cxjdavin/tgchessbot/issues/1) but there is a pull request (see https://github.com/cxjdavin/tgchessbot/pull/7) to fix that.
I guess that after your last valid move tgchessbot replied "Check!" ?.

**Comment by cxjdavin** [comment]
See: https://github.com/cxjdavin/tgchessbot/pull/7
Thanks @skrwt :)
