### ISSUE TITLE
Can't move Pawn to 8 (or 1) line.

### ISSUE THREAD

**Issue by who0ps** [cxjdavin/tgchessbot#6]
![default](https://cloud.githubusercontent.com/assets/17404606/23093797/4b9b1ce2-f5f5-11e6-93d5-8bb8d6dacde2.png)

**Comment by who0ps** [comment]
Up.

**Comment by who0ps** [comment]
UP.

**Comment by vesatoivonen** [comment]
You seem to be missing the piece you want to promote your pawn to.
Try `b7b8Q` or `b8Q` for queen.
